package dev.lunartear.host.patch.apk

import android.content.Context
import com.android.apksig.ApkSigner
import com.android.apksig.ApkVerifier
import java.io.File
import java.security.KeyStore
import java.security.PrivateKey
import java.security.cert.X509Certificate

/** Where the signing key came from, for the UI to show. */
data class SigningIdentity(val alias: String, val subject: String, val sha256: String)

/**
 * Signs the patched APK with apksig - the same library the `apksigner` CLI and
 * the Android build tools use, so the output is what the platform expects.
 *
 * The key is a throwaway PKCS#12 keystore generated by tools/gen-keystore.ps1
 * and shipped as an asset. It is deliberately not the user's own key: patched
 * clients are a research artifact, not something to distribute.
 */
object ApkSigning {

    const val KEYSTORE_ASSET = "lunar-tear-debug.keystore"
    const val KEYSTORE_PASSWORD = "lunartear"
    const val KEY_ALIAS = "lunartear"

    /** Reads the keystore from assets into memory (it is a few KB). */
    fun loadKeystore(context: Context, assetName: String = KEYSTORE_ASSET): KeyStore {
        val bytes = runCatching {
            context.assets.open(assetName).use { it.readBytes() }
        }.getOrElse {
            throw IllegalStateException(
                "signing keystore '$assetName' is missing from the APK; " +
                    "run: powershell -ExecutionPolicy Bypass -File tools\\gen-keystore.ps1",
                it,
            )
        }
        val keyStore = KeyStore.getInstance("PKCS12")
        keyStore.load(bytes.inputStream(), KEYSTORE_PASSWORD.toCharArray())
        return keyStore
    }

    fun identity(keyStore: KeyStore, alias: String = KEY_ALIAS): SigningIdentity {
        val certificate = keyStore.getCertificate(alias) as X509Certificate
        val digest = java.security.MessageDigest.getInstance("SHA-256")
            .digest(certificate.encoded)
            .joinToString("") { "%02x".format(it) }
        return SigningIdentity(alias, certificate.subjectX500Principal.name, digest)
    }

    /**
     * Signs [input] into [output] with the v2 and v3 schemes.
     *
     * **v1 (JAR signing) is deliberately disabled.** When apksig performs v1
     * signing it rewrites the archive to insert `META-INF/MANIFEST.MF` and the
     * `.SF`/`.RSA` files, which shifts every entry and destroys the page
     * alignment of the uncompressed native libraries - and the installer rejects
     * such an APK with `INSTALL_FAILED_INVALID_APK: Failed to extract native
     * libraries`. The v2 scheme covers API 24+, which is exactly this client's
     * minSdkVersion, so v1 would add nothing. (This is also what the `apksigner`
     * CLI does by default: it only enables v1 when minSdkVersion < 24.)
     */
    fun sign(
        keyStore: KeyStore,
        input: File,
        output: File,
        alias: String = KEY_ALIAS,
    ) {
        val privateKey = keyStore.getKey(alias, KEYSTORE_PASSWORD.toCharArray()) as PrivateKey
        @Suppress("UNCHECKED_CAST")
        val certificates = keyStore.getCertificateChain(alias).map { it as X509Certificate }

        val signer = ApkSigner.SignerConfig.Builder(alias, privateKey, certificates).build()
        val apkSigner = ApkSigner.Builder(listOf(signer))
            .setInputApk(input)
            .setOutputApk(output)
            .setV1SigningEnabled(false)
            .setV2SigningEnabled(true)
            .setV3SigningEnabled(true)
            .setMinSdkVersion(24)
            // apksig rewrites the archive, which by default loses the page
            // alignment of uncompressed libraries - and the installer then fails
            // with INSTALL_FAILED_INVALID_APK. Preserve the offsets we produced,
            // and page-align any uncompressed library it touches itself.
            .setAlignmentPreserved(true)
            .setLibraryPageAlignmentBytes(4096)
            .build()
        apkSigner.sign()
    }

    /** Verifies the signature of [apk] the way the platform would. */
    fun verify(apk: File, minSdkVersion: Int = 24): ApkVerifier.Result {
        val verifier = ApkVerifier.Builder(apk)
            .setMinCheckedPlatformVersion(minSdkVersion)
            .build()
        return verifier.verify()
    }

    /** One-line summary of a verification result. */
    fun describe(result: ApkVerifier.Result): String = buildString {
        append(if (result.isVerified) "verified" else "NOT verified")
        if (result.isVerified) {
            append(" (v1=${result.isVerifiedUsingV1Scheme}, v2=${result.isVerifiedUsingV2Scheme}, v3=${result.isVerifiedUsingV3Scheme})")
        }
        result.errors.forEach { append("\n  error: ").append(it) }
        result.warnings.forEach { append("\n  warning: ").append(it) }
    }
}
