package dev.lunartear.host.patch.apk

// GENERATED by tools/gen-manifest-attrs.ps1 - do not edit by hand.
//
// android:* manifest attribute resource ids, taken from the platform
// android.jar by letting aapt2 compile a probe manifest and decoding the
// result. The AXML editor needs the *resource id* (not just the name) because
// that is what the platform matches attributes on.
//
// Regenerate with:
//   powershell -ExecutionPolicy Bypass -File tools\gen-manifest-attrs.ps1
object AxmlAttrs {
    /** The namespace string that appears in the string pool for android:* attributes. */
    const val ANDROID_NS = "http://schemas.android.com/apk/res/android"

    const val TYPE_REFERENCE = 0x01
    const val TYPE_STRING = 0x03
    const val TYPE_INT_DEC = 0x10
    const val TYPE_INT_HEX = 0x11
    const val TYPE_INT_BOOLEAN = 0x12

    // aapt2 encodes a boolean true as 0xFFFFFFFF (not 1) - see the
    // 'boolean attribute encoding matches what aapt2 writes' unit test, which
    // compares our output against a probe manifest compiled by aapt2 itself.
    const val VALUE_TRUE = -1
    const val VALUE_FALSE = 0
    const val NO_RAW_VALUE = -1

    const val DEBUGGABLE = 0x0101000F
    const val EXTRACT_NATIVE_LIBS = 0x010104EA
    const val LABEL = 0x01010001
    const val MIN_SDK_VERSION = 0x0101020C
    const val NAME = 0x01010003
    const val NETWORK_SECURITY_CONFIG = 0x01010527
    const val TARGET_SDK_VERSION = 0x01010270
    const val USES_CLEARTEXT_TRAFFIC = 0x010104EC
    const val VERSION_CODE = 0x0101021B
    const val VERSION_NAME = 0x0101021C
}
