<#
.SYNOPSIS
  Derives the android:* manifest attribute resource ids from aapt2 and emits
  them as Kotlin constants.

.DESCRIPTION
  The APK patcher has to add an attribute to a *binary* AndroidManifest.xml. The
  attribute is matched by the platform by resource id, so the id must be right
  and must come from the toolchain that Android itself uses - not from memory.

  This script compiles a probe manifest with aapt2 (which assigns the ids from
  the platform android.jar), decodes the result with aapt2, and writes
  app/src/main/java/dev/lunartear/host/patch/apk/AxmlAttrs.kt.

  Everything is written inside the repository: aapt2 (like protoc's plugins) is
  denied writes elsewhere.
#>
[CmdletBinding()]
param(
    [string]$CompileSdk = '35',
    [string]$BuildTools = '35.0.0'
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$Cache    = Join-Path $PSScriptRoot '.cache'
$Aapt2    = Join-Path $Cache "sdk\build-tools\$BuildTools\aapt2.exe"
$AndroidJar = Join-Path $Cache "sdk\platforms\android-$CompileSdk\android.jar"
$Work     = Join-Path $Cache 'axmlprobe'
$OutKt    = Join-Path $RepoRoot 'app\src\main\java\dev\lunartear\host\patch\apk\AxmlAttrs.kt'

if (-not (Test-Path $Aapt2)) { throw "aapt2 not found at $Aapt2 - run tools\bootstrap-sdk.ps1" }
if (-not (Test-Path $AndroidJar)) { throw "android.jar not found at $AndroidJar" }
New-Item -ItemType Directory -Force $Work | Out-Null

# Every attribute the app reads or writes. Keep in sync with AxmlAttrs usage.
$wanted = @(
    'usesCleartextTraffic',
    'networkSecurityConfig',
    'extractNativeLibs',
    'targetSdkVersion',
    'minSdkVersion',
    'versionCode',
    'versionName',
    'debuggable',
    'label',
    'name'
)

$manifest = @"
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="dev.lunartear.probe"
    android:versionCode="152"
    android:versionName="3.7.1">
    <uses-sdk android:minSdkVersion="24" android:targetSdkVersion="$CompileSdk" />
    <application
        android:usesCleartextTraffic="true"
        android:extractNativeLibs="false"
        android:networkSecurityConfig="@xml/network_security_config"
        android:debuggable="false"
        android:label="probe">
        <activity android:name=".Probe" android:label="probe" />
    </application>
</manifest>
"@
Set-Content -Path (Join-Path $Work 'AndroidManifest.xml') -Value $manifest -Encoding utf8

# networkSecurityConfig is a reference to a real resource, so the probe needs one;
# aapt2 refuses to link a dangling @xml/ reference.
$resXml = Join-Path $Work 'res\xml'
New-Item -ItemType Directory -Force $resXml | Out-Null
Set-Content -Path (Join-Path $resXml 'network_security_config.xml') -Encoding utf8 -Value @'
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
'@

$resZip = Join-Path $Work 'res.zip'
Remove-Item $resZip -ErrorAction SilentlyContinue
& $Aapt2 compile --dir (Join-Path $Work 'res') -o $resZip 2>&1 | ForEach-Object { "  $_" }
if ($LASTEXITCODE -ne 0) { throw 'aapt2 compile failed' }

$probeApk = Join-Path $Work 'probe.apk'
Remove-Item $probeApk -ErrorAction SilentlyContinue
& $Aapt2 link -o $probeApk --manifest (Join-Path $Work 'AndroidManifest.xml') -I $AndroidJar $resZip `
    --min-sdk-version 24 --target-sdk-version $CompileSdk 2>&1 | ForEach-Object { "  $_" }
if ($LASTEXITCODE -ne 0 -or -not (Test-Path $probeApk)) { throw 'aapt2 link failed' }

$dump = & $Aapt2 dump xmltree --file AndroidManifest.xml $probeApk 2>&1
$ids = @{}
foreach ($line in $dump) {
    $m = [regex]::Match($line, 'android:([A-Za-z0-9_]+)\(0x([0-9a-fA-F]{8})\)')
    if ($m.Success) {
        $name = $m.Groups[1].Value
        if ($wanted -contains $name -and -not $ids.ContainsKey($name)) {
            $ids[$name] = $m.Groups[2].Value.ToUpperInvariant()
        }
    }
}

$missing = $wanted | Where-Object { -not $ids.ContainsKey($_) }
if ($missing) { throw "aapt2 did not report ids for: $($missing -join ', ')" }

$rows = $wanted | Sort-Object | ForEach-Object {
    $const = ($_ -creplace '([a-z0-9])([A-Z])', '$1_$2').ToUpperInvariant()
    "    const val $const = 0x$($ids[$_])"
}

$content = @"
package dev.lunartear.host.patch.apk

// GENERATED by tools/gen-manifest-attrs.ps1 - do not edit by hand.
//
// android:* manifest attribute resource ids, taken from the platform
// android.jar by letting aapt2 compile a probe manifest and decoding the
// result. The AXML editor needs the *resource id* (not just the name) because
// that is what the platform matches attributes on.
//
// Regenerate with:
//   powershell -ExecutionPolicy Bypass -File tools\gen-manifest-attrs.ps1
object AxmlAttrs {
    /** The namespace string that appears in the string pool for android:* attributes. */
    const val ANDROID_NS = "http://schemas.android.com/apk/res/android"

    const val TYPE_REFERENCE = 0x01
    const val TYPE_STRING = 0x03
    const val TYPE_INT_DEC = 0x10
    const val TYPE_INT_HEX = 0x11
    const val TYPE_INT_BOOLEAN = 0x12

    // aapt2 encodes a boolean true as 0xFFFFFFFF (not 1) - see the
    // 'boolean attribute encoding matches what aapt2 writes' unit test, which
    // compares our output against a probe manifest compiled by aapt2 itself.
    const val VALUE_TRUE = -1
    const val VALUE_FALSE = 0
    const val NO_RAW_VALUE = -1

$($rows -join "`n")
}
"@

Set-Content -Path $OutKt -Value $content -Encoding utf8
Write-Host "[attrs] wrote $OutKt"
$ids.GetEnumerator() | Sort-Object Name | ForEach-Object { "  {0,-24} 0x{1}" -f $_.Key, $_.Value }
